package com.imooc.community.mapper;

import com.imooc.community.model.Quseetion;
import com.imooc.community.model.QuseetionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface QuseetionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    long countByExample(QuseetionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int deleteByExample(QuseetionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int insert(Quseetion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int insertSelective(Quseetion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    List<Quseetion> selectByExampleWithBLOBsWithRowbounds(QuseetionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    List<Quseetion> selectByExampleWithBLOBs(QuseetionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    List<Quseetion> selectByExampleWithRowbounds(QuseetionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    List<Quseetion> selectByExample(QuseetionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    Quseetion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") Quseetion record, @Param("example") QuseetionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Quseetion record, @Param("example") QuseetionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int updateByExample(@Param("record") Quseetion record, @Param("example") QuseetionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int updateByPrimaryKeySelective(Quseetion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Quseetion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Mar 19 10:58:12 CST 2020
     */
    int updateByPrimaryKey(Quseetion record);
}